spring.application.name=todo_project_boot
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=todoList_boot
spring.datasource.password=todoList1234
server.port=80
spring.config.import=classpath:config.properties
mybatis.configuration.map-underscore-to-camel-case=true
